In [1]:
import pandas as pd
from NLPWash import textscrub

In [2]:
df = pd.read_csv(r'D:\NMIMS-Hiten\NLP\Disaster Tweets\train.csv')
df.head()

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1

In [3]:
a = textscrub.TextProcessor()

df['normalized_text'] = df['text'].apply(a.normalize_text,
                                        lowercase=True,
                                        tokenization=True,
                                        remove_stopwords=True,
                                        remove_emojis=True,
                                        remove_html_tags = True,
                                        remove_punctuation=True,
                                        remove_hyperlinks= True,
                                        stemming = 'SnowballStemmer',
                                        lemmatizing=True)
df.head()

[nltk_data] Downloading package punkt to C:\Users\nitro
[nltk_data]     5\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\nitro
[nltk_data]     5\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\nitro
[nltk_data]     5\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\nitro
[nltk_data]     5\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

,id,keyword,location,text,target,normalized_text
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1,deed reason earthquak may allah forgiv u
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1,forest fire near la rong sask canada
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1,resid ask shelter place notifi offic evacu she...
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1,13000 peopl receiv wildfir evacu order califor...
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1,got sent photo rubi alaska smoke wildfir pour ...